#+TITLE: Tommy Wang's Home Page
#+AUTHOR: Tommy Wang
#+OPTIONS: num:nil toc:nil

#+HTML_HEAD_EXTRA: <style type="text/css">
#+HTML_HEAD_EXTRA: <!--/*--><![CDATA[/*><!--*/
#+HTML_HEAD_EXTRA: h1.title, #table-of-contents h2 { display:none; }
#+HTML_HEAD_EXTRA: #text-table-of-contents {margin-left: 100px; height:160px; }
#+HTML_HEAD_EXTRA: #text-table-of-contents ul { list-style-type: none; }
#+HTML_HEAD_EXTRA: /*]]>*/-->
#+HTML_HEAD_EXTRA: </style>


#+ATTR_HTML: :width 120 :style float:left;
[[file:images/me.depth][file:./images/me.png]]
#+TOC: headlines 1

* 
  + 1977年生于四川，长于甘肃，大学毕业于陕西，现和妻子，女儿，指针（我的爱犬）定居在北京。
  + 目前在一家科技公司做技术负责人，技术领域不太固定，但始终奋斗在编程的最前线，很幸苦，但很享受。
  + 最常用的网名是 bitorb, 工作中有时会使用我的英文名 Tommy。
  + 我的 Mail : bitorb AT gmail DOT com，我在网络社交方面比较保守，几乎不用微博、微信、QQ 等应用。
  + 我的 GPG Key Fingerprint : [[http://pgp.mit.edu:11371/pks/lookup?search%3D0xA565F2C2&amp%3Bop%3Dindex][573F C15E B6A4 8432 EA49   FA77 E05C CC56 A565 F2C2]]


本站的部分外链有时可能无法正常访问，希望你有点崂山道士的本领，我甚至觉得这是目前国内技术同行必须掌握的一项基本技能。
* 目前业余时间的开销
  + 遛狗，长假时与家人出游。
  + 看小说，偶尔看电视，没事就整理我的几台电脑，更多的时间是发呆。
* 程序与文档
  下列所有程序和文档的源码分别存放在 [[http://code.google.com][Google Code]]， [[http://github.com][GitHub]]， [[http://java.net][Java.net]]。 
  如果没有特殊声明，下面程序都采用 [[http://www.apache.org/licenses/LICENSE-2.0.txt][Apache License, Version 2.0]] 发布。所有文档都采用 [[http://www.gnu.org/licenses/fdl.txt][GNU 自由文档许可证, Version 1.3]] 发布。
  + [[https://github.com/bitorb/gaixie][gaixie]] : 
    所有 [[http://maven.apache.org][Maven]] 结构的项目的根。我所有的 Maven 项目都需要继承它，最后发布到 [[http://repo1.maven.org/maven2/org/gaixie/][Maven 中心仓库]]。
  + [[https://github.com/bitorb/jibu][jibu]] : 
    一个基于 [[http://code.google.com/p/google-guice/][Guice]] 和 [[http://www.sencha.com/products/extjs/][ExtJS]] 的超轻量级开源框架，已经成功应用到多个项目，可以从 [[http://repo1.maven.org/maven2/org/gaixie/jibu/assemblies/jibu/][这里下载]] 最新的编译好的打包文件。 
  + [[https://github.com/bitorb/jibu-doc][jibu-doc]] : 
    以 [[http://docbook.org][Docbook]] 格式编写的 Jibu 项目文档源码。
  + [[https://github.com/bitorb/bitorb][bitorb]] : 
    我自己的 Linux 和 Mac OS X 的相关配置文件及脚本，主要是为了重装机器方便。
  + [[https://github.com/bitorb/bitorb-org][bitorb-org]] : 
    我个人主页的源码，用 [[http://orgmode.org][Emacs Orgmode]] 编写，导出的静态页面在 [[https://github.com/bitorb/bitorb.github.io][bitorb.github.io]] 中版本化。
  + [[https://github.com/bitorb/bitorb.github.io][bitorb.github.io]] : 
    [[http://gaixie.org][Gaixie.ORG]] 网站静态页面，含我的个人主页静态页面，通过 github 的 pages 功能展示。


  有一些篇幅不是特别长，需要长期维护的技术文档，请 [[./docs/index.org][从这里进入]]。
