#+TITLE: ~ / 文档 / 重装系统时习惯的设置
#+AUTHOR: Tommy Wang
#+OPTIONS: ^:nil

#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="../css/org.css">

* 所有系统
** Google Chrome 的同步设置
   设置 --> 高级同步设置 --> 选择要同步的数据类型
   
   只勾选：
   + 已保存的书签

** SSH 私钥导入
   无论什么操作系统，安装后我首先做的就是导入 SSH 私钥。
#+BEGIN_EXAMPLE
$ mkdir ~/.ssh
$ chmod 700 ~/.ssh/
$ cp id_rsa ~/.ssh
$ chmod 600 ~/.ssh/id_rsa
#+END_EXAMPLE

** 建立一个用来进行源码编译的目录
   Linux 通常默认已经有 /usr/local/src 目录，只需设下权限，以后编译可少输几个 sudo。
   Mac OSX 默认没有，需要创建一个。
#+BEGIN_EXAMPLE
$ sudo mkdir /usr/local/src
$ sudo chown $USER /usr/local/src/
$ sudo chmod u+rwx /usr/local/src/
#+END_EXAMPLE

** 使用 Google Noto 字体
   进入 [[https://www.google.com/get/noto/][Google Noto 字体官网]]，下载字体包，然后根据教程对不同的操作系统进行设置，很简单。对我来说，主要的目的是在各种系统下，生成的 pdf 文档风格统一美观。
   或者单独下载中文字体文件包，下面的 ttc 适用于 Mac OSX。
#+BEGIN_EXAMPLE
$ curl -O https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJK.ttc.zip
$ curl -O https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJK.ttc.zip
#+END_EXAMPLE
如果用的是 Debian 系统，虽然能加载 ttc，但通过 latex 调用字体时会报错，所以只能的单独下载 otf 文件。
#+BEGIN_EXAMPLE
$ curl -O https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip
$ curl -O https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKsc-hinted.zip
#+END_EXAMPLE

* Linux
** 修改主机名
   hostnamectl 命令会在 /etc 目录下生成一个 hostname 文件。
#+BEGIN_EXAMPLE
$ hostnamectl set-hostname tomt60p.gaixie.org
#+END_EXAMPLE

** Debian Mate 环境变量
   目前常用的 Linux 系统是 Debian，桌面用的 Mate，因为进入 X 不会加载 .bash_profile 文件，每次都手工 source 加载，很不方便。决定改一下，
方法就是做一个 environment 文件，将 OSX 和 Linux 都会用到的环境变量设置放在这个文件里，但后在各自系统默认的配置文件以 source 方式加载，而不是之前的软链接的方式。
Debian 桌面启动是默认会加载 ~/.bashrc 文件，所以使用下面的命令。
#+BEGIN_EXAMPLE
$ echo 'source ~/Projects/gaixie/bitorb/environment' >> ~/.bashrc
#+END_EXAMPLE
   参考文档：
   + https://unix.stackexchange.com/questions/88106/why-doesnt-my-bash-profile-work
* Mac OSX
** 修改显示的主机名
   不太喜欢 Mac 下 Terminal 窗口显示的主机名，如果是 MacBook Pro 我会用下面命令把它改为 tommbp.local，若不加
   .local 的后缀，emacs 启动相当的慢。
#+BEGIN_EXAMPLE
$ scutil --get HostName
$ sudo scutil --set HostName tommbp.local
#+END_EXAMPLE 
   参考文档：
   + [[http://apple.stackexchange.com/questions/66611/how-to-change-computer-name-so-terminal-displays-it-in-mac-os-x-mountain-lion][How to change computer name so terminal displays it in Mac OS X]]

** 环境变量设置
   和 Linux 下环境变量设置的方式一样，只不过 OSX 下加载的是 ~/.bash_profile 文件。
#+BEGIN_EXAMPLE
$ echo 'source ~/Projects/gaixie/bitorb/environment' >> ~/.bash_profile
#+END_EXAMPLE
   参考文档：
   + https://apple.stackexchange.com/questions/119711/why-doesnt-mac-os-x-source-bashrc/119713
